### ISSUE TITLE
Integration of Eclipse Zenoh into Eclipse SDV FMS Blueprint

### ISSUE THREAD

**Issue by pgangula-src** [eclipse-sdv-blueprints/fleet-management#22]
Dear all,

I apologize for the delay, but I now have the details regarding the expected Zenoh integration in the FMS blueprint. We will submit the PR in coming days that addresses the step 1 (see below), and I would appreciate your patience and constructive feedback, as this is my first time contributing here.

**Objective:**

This issue is created to initiate the integration of Eclipse Zenoh into the Eclipse SDV FMS blueprint. The inclusion of Eclipse Zenoh offers a unified interface for accessing VSS (Vehicle Signal Specification) data via Kuksa, leading to several advantages:

- **Streamlined Communication:** The integration will streamline communication, reducing the number of hops required and thereby minimizing the complexity of the software 
artifacts.
- **Efficient Data Distribution:** Zenoh allows efficient data distribution in proximity to the edge, making it well-suited for the demands of the Fleat Management Systems.
- **Protocol Plugins:** Zenoh Router is equipped with plugins for various protocols and databases, facilitating seamless communication with other components if needed.

**Proposed Changes:**

The integration of Eclipse Zenoh into the FMS blueprint will be realized in two steps:

**Step 1:  Extend FMS Forwarder to publish data in Zenoh and configure Zenoh Router to also receive data over MQTT**

- Assess the current FMS Forwarder and identify the necessary modifications to enable data publication through Zenoh.
- Implement the required code changes to publish data via Zenoh.
- MQTT plugin configuration on the Zenoh Router to as well support MQTT interfaces.

**Step 2: FMS consumer Integration in Zenoh Router**

- Implement the necessary changes in Zenoh Router using Zenoh Flow to create components that publish / consume data into influxdb.

**Blueprint Suggestion:**
![architecture-zenoh-latest drawio_latest_v1 0](https://github.com/eclipse-sdv-blueprints/fleet-management/assets/59826473/0c0ce9a2-23dd-4b54-9b0d-4a4e1a8a3a85)

**Comment by sophokles73** [comment]
Thanks for the proposal :+1: 

I do not think that I fully understand the steps involved, though. Are the two steps supposed to each result into a usable system based on Zenoh? Or do both steps need to be implemented before Zenoh can be used?

**Comment by pgangula-src** [comment]
Step 1 already allows you to obtain the raw protobuf data through Zenoh and publish it to anywhere. 
Step 2 primarily facilitates the storage of data in InfluxDB according to the relevant measurements.

**Comment by sophokles73** [comment]
> Step 1 already allows you to obtain the raw protobuf data through Zenoh and publish it to anywhere.

Why would I want to let the FMS Forwarder publish data to a Zenoh router, if the data is not being processed by any component?

**Comment by pgangula-src** [comment]
The FMS Forwarder is currently transmitting unprocessed data via MQTT, and we are also offering an alternative option through Zenoh. I wonder what is the question here..

**Comment by sophokles73** [comment]
Ok, then step 1 is replacing the direct (MQTT) connection between the FMS Forwarder and the Hono MQTT Adapter with a connection via the Zenoh Router, right?
In such a setup the Zenoh router would need to be able to connect to the Hono MQTT Adapter and publish data to the proper topics. Is that what you have in mind?

**Comment by pgangula-src** [comment]
Zenoh Router gets the data from FMS Forwarder over MQTT or Zenoh (see picture above) and processes it and puts that information into InfluxDB. Thats the scope here and we do not need to connect to Hono MQTT Adapter.

**Comment by sophokles73** [comment]
> Zenoh Router gets the data from FMS Forwarder over MQTT or Zenoh (see picture above) and processes it and puts that information into InfluxDB.

In the picture above, the Zenoh router seems to require the FMS Consumer to speak Zenoh to receive the messages from the FMS Forwarder. The FMS Consumer then writes the data to Influx. To me, this looks like the outcome of an additional 3rd step? But it does not seem to reflect the outcome of step 2. That's why I'm asking ...

**Comment by pgangula-src** [comment]
The idea is to include FMS consumer logic into the Router directly using Zenoh Flow. Sorry for the confusion i could perhaps suggest a better picture that makes it clear.
"Step 2: FMS consumer Integration in Zenoh Router"

**Comment by sophokles73** [comment]
Ok, now I got it. Thanks for your patience ;-)

**Comment by sophokles73** [comment]
@pgangula-src can you maybe update the picture so that it reflects the intended target state? Otherwise, I believe that others will also struggle a lot with getting the idea ...

**Comment by pgangula-src** [comment]
Done.!
