### ISSUE TITLE
add Copyright Header

### ISSUE THREAD

**Issue by eriksven** [eclipse-sdv-blueprints/fleet-management#45]
Some files in this fleet-management repository currently do not have copyright headers. This seems to involve the files that have been added with #36 . @vivekpandey02 could you please so kind to review whether you can add a copyright and license header for the Apache 2.0 license used in the rest of the repository?

One example would be the header used here: https://github.com/eclipse-sdv-blueprints/fleet-management/blob/main/fms-blueprint-compose.yaml

**Comment by vivekpandey02** [comment]
> Some files in this fleet-management repository currently do not have copyright headers. This seems to involve the files that have been added with #36 . @vivekpandey02 could you please so kind to review whether you can add a copyright and license header for the Apache 2.0 license used in the rest of the repository?
> 
> One example would be the header used here: https://github.com/eclipse-sdv-blueprints/fleet-management/blob/main/fms-blueprint-compose.yaml

Hello @eriksven, I've inserted the copyright headers into the files that I added for zenoh support. Please let me know if everything is satisfactory now.

**Comment by eriksven** [comment]
Looks good to me, thank you for the quick reaction.
